name: Build macOS app

on:
  push:
    branches: [KeyFeature] # or change to your branch

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build macOS app
        run: npm run build:mac

      - name: Upload .dmg file
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: dist/*.dmg
